[project]
name = "Picard Plugins"
version = "0.1.0"
description = "Various picard plugins"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "picard>=2.13.3",
    "pykakasi>=2.3.0",
]
